WINDOW_HEIGHT = 720
WINDOW_WIDTH = 1280

VIRTUAL_WIDTH = 256
VIRTUAL_HEIGHT = 144

TILE_SIZE = 16

PLAYER_WIDTH = 16
PLAYER_HEIGHT = 20

GROUND = 3
SKY = 5
PLATFORM = 0 -- special id

COLLIDABLE_TILES = {GROUND, PLATFORM}

PLAYER_MOVE_SPEED = 60
SNAIL_MOVE_SPEED = 25
SNAIL_CHASE_SPEED = 35

CAMERA_SCROLL_SPEED = 40